### ISSUE TITLE
When to Choose Calorimeter Name

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2797]
~~In the calorimeter plugin, the `filter` is encoded *twice* in the filename, e.g.:~~

In the calorimeter plugin, we don't yet doc how (and when) to chose a `.file`-name, e.g.:

```
simOutput/H_calorimeter/all/H_calorimeter_<file>_all_12000_0_0_0.h5
```

The order of arguments is also a bit off, we usually write:
```
<species>_<filter>_...
```
directly together.

seen in PIConGPU 0.4.1

**Comment by psychocoderHPC** [comment]
This is not a bug could it be that you named the output file `--H_calorimeter.file "all"`

The name of the file is created out of `<species>_<pluginname>_<file>_<filter>_<timestep>_<mpiposition>.h5`

**Comment by ax3l** [comment]
Ah yes, I was probably over-cautious in the file name!

**Comment by psychocoderHPC** [comment]
We can add `<species>_<pluginname>_<file>_<filter>_<timestep>_<mpiPosition>.h5` to https://picongpu.readthedocs.io/en/0.4.1/usage/plugins/particleCalorimeter.html#output but I would try to keep it short.
A drawback is that it is very fast outdated e.g. as soon as we change to output method to the OpenPMD-api.

**Comment by ax3l** [comment]
`<pluginname>` is fixed to `calorimeter` ;-)

We should adjust it to `<species>_<filter>_calorimeter_<suffix>_<timestep>_<mpiposition>.h5` and can update it anytime when the output method should be changed in the future.

**Comment by ax3l** [comment]
Will provide two PRs, one docing the current `dev` and one updating the order.

**Comment by psychocoderHPC** [comment]
I know that we can update it any time but the potential to miss it is high.
Never the less you missed the filename in the description.

**Comment by psychocoderHPC** [comment]
Normally `_calorimeter` can be removed from the file name because we have it in the folder hierarchy but we discussed it in the passed and you said you like to keep it in the file name.

**Comment by ax3l** [comment]
> I know that we can update it any time but the potential to miss it is high.

There is more to update for a plugin if we change it's I/O routines ;-) E.g. post-processing libraries. Currently, this plugin does not even write openPMD since openPMD 1.* can only describe spatial meshes.

**Comment by psychocoderHPC** [comment]
closed with #2800

**Comment by ax3l** [comment]
nope, I still want to change the order in `dev` for the filename.

**Comment by ax3l** [comment]
oh weird, we *do* suffix the filter. In that case it's done :)
